Update system to use Ubuntu 14.04.3 release
* Canonical changed the initrd casper boot script
  between 14.04.2 and 14.04.3, requiring forward
  porting of custom casper changes.

diff --git a/custom/casper/casper b/custom/casper/casper
--- a/custom/casper/casper
+++ b/custom/casper/casper
@@ -375,12 +375,67 @@ try_snap ()
     return 0
 }
 
+cow_write_format() {
+    {
+        echo "# This records the union filesystem format used for this cow medium; do not delete or alter."
+        echo "UNIONFS=$1"
+    } >"$2"
+}
+
 setup_unionfs() {
     image_directory="$1"
     rootmnt="$2"
 
+    # Mount up the writable layer, if it is persistent then it may well
+    # tell us what format we should be using.
+    mkdir -p /cow
+    cowdevice="tmpfs"
+    cow_fstype="tmpfs"
+    cow_mountopt="rw,noatime,mode=755"
+
+    # Looking for "${root_persistence}" device or file
+    if [ -n "${PERSISTENT}" ]; then
+        cowprobe=$(find_cow_device "${root_persistence}")
+        if [ -b "${cowprobe}" ]; then
+            cowdevice=${cowprobe}
+            cow_fstype=$(get_fstype "${cowprobe}")
+            cow_mountopt="rw,noatime"
+        else
+            [ "$quiet" != "y" ] && log_warning_msg "Unable to find the persistent medium"
+        fi
+    fi
+
+    mount -t ${cow_fstype} -o ${cow_mountopt} ${cowdevice} /cow || panic "Can not mount $cowdevice on /cow"
+
+    # Work out if this is an existing persistance partition and if so
+    # move its existing "upper" into a new upper directory.
+    if [ ! -d /cow/upper ]; then
+        mkdir -p /cow/upper
+        for cow_content in /cow/*
+        do
+            case "$cow_content" in
+            /cow/lost+found|/cow/upper)     continue ;;
+            esac
+
+            mv "$cow_content" /cow/upper
+
+            # We have no format information, so fake some up.  If they
+            # have not specified any then we simply assume it was
+            # overlayfs (V1 format).
+            cow_write_format "overlayfs" /cow/format
+        done
+    fi
+    mkdir -p /cow/work
+
+    # Look and see if we have a current format, it is essential we use
+    # a compatible format.  Relies on the recovery above having cleaned
+    # out the top level.
+    [ -f /cow/format ] && . /cow/format
+
+    # See if we have the appropriate format, pick the first one if
+    # unspecified.
     if [ "${UNIONFS}" = 'DEFAULT' ]; then
-        for union in 'overlayfs' 'aufs' 'unionfs'
+        for union in 'overlay' 'overlayfs' 'aufs' 'unionfs'
         do
             modprobe "${MP_QUIET}" -b ${union} || true
             if cut -f2 /proc/filesystems | grep -q "^${union}\$"; then
@@ -396,6 +451,15 @@ setup_unionfs() {
     if [ "${UNIONFS}" = 'DEFAULT' ]; then
         UNIONFS='aufs'
     fi
+    # Confirm the final format was valid.
+    if [ "${UNIONFS}" != "unionfs-fuse" ]; then
+        modprobe "${MP_QUIET}" -b "${UNIONFS}" || true
+        if cut -f2 /proc/filesystems | grep -q "^${UNIONFS}\$"; then
+            :
+        else
+            panic "/cow format specified as ${UNIONFS} and no support found"
+        fi
+    fi 
 
     # run-init can't deal with images in a subdir, but we're going to
     # move all of these away before it runs anyway.  No, we're not,
@@ -444,35 +508,18 @@ setup_unionfs() {
     done
     rofsstring=${rofsstring%:}
 
-    mkdir -p /cow
-    cowdevice="tmpfs"
-    cow_fstype="tmpfs"
-    cow_mountopt="rw,noatime,mode=755"
-
-    # Looking for "${root_persistence}" device or file
-    if [ -n "${PERSISTENT}" ]; then
-        cowprobe=$(find_cow_device "${root_persistence}")
-        if [ -b "${cowprobe}" ]; then
-            cowdevice=${cowprobe}
-            cow_fstype=$(get_fstype "${cowprobe}")
-            cow_mountopt="rw,noatime"
-        else
-            [ "$quiet" != "y" ] && log_warning_msg "Unable to find the persistent medium"
-        fi
-    fi
-
-    mount -t ${cow_fstype} -o ${cow_mountopt} ${cowdevice} /cow || panic "Can not mount $cowdevice on /cow"
-
+    # Record the format we are using for this mount.
+    [ ! -f /cow/format ] && cow_write_format "${UNIONFS}" /cow/format
     case ${UNIONFS} in
         unionfs-fuse)
-            (ulimit -n 16384; unionfs-fuse -o cow -o noinitgroups -o default_permissions -o allow_other -o use_ino -o suid /cow=RW:$rofsstring "$rootmnt" || panic "${UNIONFS} mount failed")
+            (ulimit -n 16384; unionfs-fuse -o cow -o noinitgroups -o default_permissions -o allow_other -o use_ino -o suid /cow/upper=RW:$rofsstring "$rootmnt" || panic "${UNIONFS} mount failed")
             mkdir -p /dev/.initramfs/varrun
             pidof unionfs-fuse >> /dev/.initramfs/varrun/sendsigs.omit || true
             ;;
         aufs|unionfs)
-            mount -t ${UNIONFS} -o noatime,dirs=/cow=rw:$rofsstring ${UNIONFS} "$rootmnt" || panic "${UNIONFS} mount failed"
+            mount -t ${UNIONFS} -o noatime,dirs=/cow/upper=rw:$rofsstring ${UNIONFS} "$rootmnt" || panic "${UNIONFS} mount failed"
             ;;
-        overlayfs)
+        overlay|overlayfs)
             # Mount the layers pairwise from the bottom onto rootmnt,
             # for the second and later layers rootmnt forms the lower layer.
             mounts=""
@@ -487,8 +534,10 @@ setup_unionfs() {
                     lower="$mount"
                     continue
                 fi
-                mount -t overlayfs -o "upperdir=$mount,lowerdir=$lower" \
-                    "$mount" "$rootmnt"
+                mount -t ${UNIONFS} -o "upperdir=$mount/upper,lowerdir=$lower,workdir=$mount/work" \
+                    "$mount" "$rootmnt" || \
+                  mount -t ${UNIONFS} -o "upperdir=$mount/upper,lowerdir=$lower" \
+                      "$mount" "$rootmnt"
                 lower="$rootmnt"
             done
             ;;
