Refactored branch specific scripts for config and messaging

diff --git a/config/chroot.d/50-pybombs-01-install-apps b/config/chroot.d/50-pybombs-01-install-apps
--- a/config/chroot.d/50-pybombs-01-install-apps
+++ b/config/chroot.d/50-pybombs-01-install-apps
@@ -3,10 +3,7 @@ set -o nounset
 #set -x #DEBUG
 
 cd $SCRIPT_BINDDIR
-
-. ./.config
-. config/config-vars
-. bin/chroot-functions.sh
+. bin/library.sh
 
 # Exit if already run
 [ ! -f $STAMPDIR/50-pybombs-01-install-apps.stamp ] || exit 0
@@ -15,19 +12,15 @@ cd $SCRIPT_BINDDIR
 do_pybombs_install () {
     # Test for required arguments
     if [ $# -lt 2 ] ; then
-        $PRINTERROR "Usage: $0 <PACKAGE> <GITREV>"
-        exit 1
+        die "Usage: $0 <PACKAGE> <GITREV>"
     else
         PKG=$1
         GITREV=$2
     fi
 
-    LWR=/usr/local/src/pybombs/recipes/${PKG}.lwr
     # Check LWR exists:
-    [ -r $LWR ] || {
-        $PRINTERROR "Cannot find LWR for package $PKG!"
-        exit 1
-    }
+    LWR=/usr/local/src/pybombs/recipes/${PKG}.lwr
+    [ -r $LWR ] || die "Cannot find LWR for package $PKG!"
 
     # This is where the repo is checked out by PyBOMBS:
     REPODIR=/usr/local/src/pybombs/src/$PKG
@@ -53,8 +46,7 @@ do_pybombs_install () {
     grep gitrev $LWR
     RET=$?
     if [ $RET -ge 2 ] ; then
-        $PRINTERROR Unable to access gnuradio pybombs recipe!
-        exit 1
+        die Unable to access gnuradio pybombs recipe!
     fi
     if [ $RET -eq 1 ] ; then
         sed -i -e '/gitbranch/a gitrev: '$GITREV $LWR
@@ -62,27 +54,18 @@ do_pybombs_install () {
 
     # Execute pybombs recipe to install package
     cd $ROOTFS_SRCDIR/pybombs
-    ./pybombs install $PKG || {
-        $PRINTERROR Unable to install package $PKG via pybombs!
-        exit 1
-    }
+    ./pybombs install $PKG || die Unable to install package $PKG via pybombs!
 
     # Clean up compilation results
     if [ -d $MAKEDIR ]; then
-        rm -rf $MAKEDIR || {
-            $PRINTERROR Unable to clean up after compiling package $PKG!
-            exit 1
-        }
+        rm -r $MAKEDIR || die Unable to clean up after compiling package $PKG!
     fi
 
     # Nuke repository history for git repos
     if [ -d $REPODOTDIR ]; then
-        rm -rf $REPODOTDIR || {
-            $PRINTERROR Unable to clean up repository history for package $PKG!
-            exit 1
-        }
+        rm -r $REPODOTDIR || die Unable to clean up repository history for package $PKG!
     else
-        $PRINTINFO "Repo directory $REPODOTDIR not found."
+        printwarn Repo directory $REPODOTDIR not found.
     fi
 
     # Tell the system we've possibly installed a new shared libraries
@@ -93,7 +76,7 @@ do_pybombs_install () {
 
 # Create git cache repository if needed
 if ! [ -f $GITCACHE/config ] ; then
-    $PRINTINFO Initializing git cache repository...
+    printinfo Initializing git cache repository...
     git init --bare gitcache/
 fi
 
@@ -108,18 +91,18 @@ while read LINE ; do
     FILE=$(echo $LINE | cut -f 3 -d ' ')
 
     [ -f $FILE ] || {
-        $PRINTINFO Installing component $COMP at revision $REV...
+        printinfo Installing component $COMP at revision $REV...
 
         # Check if remote repo needs adding to gitcache
         if ! git -C $GITCACHE remote | grep -q $COMP ; then
-            $PRINTINFO Adding remote repository for $COMP to gitcache...
+            printinfo Adding remote repository for $COMP to gitcache...
             REMOTE_URL=$(grep ^source: $ROOTFS_SRCDIR/pybombs/recipes/$COMP.lwr | cut -f 3- -d /)
             # Clone into temp dir to avoid long waits identifying "no common commits"
             TEMPDIR=$SCRIPT_BINDDIR`mktemp -d`
-            $PRINTINFO Cloning remote repository into tmpdir...
+            printinfo Cloning remote repository into tmpdir...
             git clone $REMOTE_URL $TEMPDIR
             # Now add this temp repo as remote to fetch from and update
-            $PRINTINFO Adding temp repository into gitcache...
+            printinfo Adding temp repository into gitcache...
             git -C $GITCACHE remote add $COMP $TEMPDIR/
             git -C $GITCACHE fetch $COMP --tags
             # Finally, set the remote to the actual remote URL
@@ -130,16 +113,13 @@ while read LINE ; do
             rm -rf $TEMPDIR/
         fi
 
-        $PRINTINFO Updating gitcache with latest commits from remote repo...
+        printinfo Updating gitcache with latest commits from remote repo...
         git -C $GITCACHE remote update -p $COMP
 
         # Check for pre-installation actions
         [ -f $SCRIPT_BINDDIR/config/pybombs.d/preinst.d/$COMP ] && {
-            $PRINTINFO Executing pre-installation script for $COMP
-            config/pybombs.d/preinst.d/$COMP || {
-                $PRINTERROR Pre-installation for $COMP failed!
-                exit 1
-            }
+            printinfo Executing pre-installation script for $COMP
+            config/pybombs.d/preinst.d/$COMP || die Pre-installation for $COMP failed!
         }
 
         # DOOO EEET! DOOO EEET NOW!
@@ -147,11 +127,8 @@ while read LINE ; do
 
         # Check for post-installation actions
         [ -f config/pybombs.d/postinst.d/$COMP ] && {
-            $PRINTINFO Executing post-installation script for $COMP
-            config/pybombs.d/postinst.d/$COMP || {
-                $PRINTERROR Post-installation for $COMP failed!
-                exit 1
-            }
+            printinfo Executing post-installation script for $COMP
+            config/pybombs.d/postinst.d/$COMP || die Post-installation for $COMP failed!
         }
     }
 done < config/pybombs.d/install.conf
